version: "3.7"
services:
  client:
    build: ./client
    ports:
      - "8082:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server
  server:
    build: ./server
    environment: 
      - PORT=5000
    ports:
      - "8081:5000"
    volumes:
      - ./server:/usr/src/app
    networks:
      - mongo-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume/db:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge